spring:
    main:
        web-application-type: servlet
    application:
        name: Task-3.1.1

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                hbm2ddl:
                    auto: update
    mvc:
        hidden method:
            filter:
                enabled: true

    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
logging:
    level:
        ru.itmentor.spring.boot_security.demo: DEBUG
#spring.jpa.hibernate.ddl-auto=create  spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect